### ISSUE TITLE
Pie Chart not rendered correctly under certain circumstances

### ISSUE THREAD

**Issue by kevinjqiu** [frappe/charts#117] opened 2018-01-17 05:40 UTC
#### Expected Behaviour
Given the following data set
```
  data = {
    labels: ["A", "B", "C"],

    datasets: [
      {
        title: "Some Data", color: "light-blue",
        values: [3126.24, 1412, 8.5]
      }
    ]
  };

  chart = new Chart({
    parent: "#chart", // or a DOM element
    title: "My Awesome Chart",
    data: data,
    type: 'pie', // or 'line', 'scatter', 'pie', 'percentage'
    height: 250
  });
```
Expect the Pie chart to be like a pie...

#### Actual Behaviour

The rendered chart looks like someone cut the pie and scrambled the pieces:

![image](https://user-images.githubusercontent.com/84321/35027523-3378e09c-fb1f-11e7-9942-96fc777a67f9.png)

#### Steps to Reproduce:
* See this jsfiddle: http://jsfiddle.net/rwq87jd7/

NOTE: Add a GIF/Screenshot if required.

Frappé Charts version:
0.0.7

**Comment by achillesrasquinha** [comment] 2018-01-17 06:21
Hi, thanks for the issue! Duplicate of #108. Let's take it there.

**Closed by achillesrasquinha** 2018-01-17 06:21 UTC
