### ISSUE TITLE
TypeError: Cannot read property 'xPos' of undefined

### ISSUE THREAD

**Issue by CristianWesleyFront** [frappe/charts#265] opened 2020-02-22 19:36 UTC
#### Expected Behaviour
Allow you to freely click the screen

#### Actual Behaviour

Uncaught TypeError: Cannot read property 'xPos' of undefined
    at e.value (AxisChart.js:408)
    at HTMLDivElement.<anonymous> (AxisChart.js:394)

#### Steps to Reproduce:
* v1.3.0 and react v16.12.0
* render line graphic 
* Click many times in and out of the graphic 

NOTE: Add a GIF/Screenshot if required.
![image](https://user-images.githubusercontent.com/26757758/75098118-281f9a00-5591-11ea-8362-afc2f46cee75.png)
![image](https://user-images.githubusercontent.com/26757758/75098148-6f0d8f80-5591-11ea-83de-c237a195a63f.png)

Frappé Charts version: 1.3.0

**Comment by trimoda** [comment] 2020-02-22 20:25
Same here.

**Comment by CristianWesleyFront** [comment] 2020-02-28 21:41
In version: 1.2.4 is working

**Comment by faburem** [comment] 2020-03-17 15:06
I am experiencing the same issue and can also confirm that this is working fine in version 1.2.4 so it seems to be a regression in 1.3.0.

**Comment by Groxan** [comment] 2020-03-21 09:50
I've faced the same issue. 

Just wanted to clarify that in my case an exception is thrown when you move the mouse to the left of the first point (in the y-axis labels area).

![frappe-chart](https://user-images.githubusercontent.com/7966898/77223966-47025380-6b72-11ea-8218-e64682471a5e.gif)

**Comment by trimoda** [comment] 2020-03-26 08:56
Still no solution?

**Comment by trimoda** [comment] 2020-03-26 17:14
Still no solution?

**Comment by bmuller** [comment] 2020-04-30 01:29
Hey @scmmishra - thanks for an awesome project!  This seems to be a duplicate of #248, which was fixed a while ago.

I'd love to use this lib in a big project - but can't as long as there's no new release on NPM.  This (and many other) bugs have been fixed, can you publish at least a minor version bump?  Thanks!

**Comment by scmmishra** [comment] 2020-04-30 09:48
Yeah, the fix was merged a while ago. I've released 1.3.2 with multiple new fixes.

**Closed by scmmishra** 2020-04-30 09:48 UTC

**Comment by bmuller** [comment] 2020-04-30 12:40
Great - thanks so much @scmmishra !
